### ISSUE TITLE
POD: obscure "Quick Reference" section

### ISSUE THREAD

**Issue by dolmen** [kentnl/Dist-Zilla-Plugin-MetaProvides-Package#4]
The [POD for DZP::MetaProvides::Package](https://metacpan.org/pod/Dist::Zilla::Plugin::MetaProvides::Package#QUICK-REFERENCE) has an obscure QUICK REFERENCE section that seems only useful to the plugin author.
It would be helpful to at least add a link to some documentation about how to decode it.

**Comment by kentfredric** [comment]
Its kindof only in concept stage and needs to be less hand-generated :) 

Its just a top-down view of all accessible methods and attributes broken down by composition, with some ideas borrowed from ruby syntax, but also chosen for how it probably highlights. 

Some details don't really need to be shown really, but it is still just a concept I'm kicking around.

```
->new(options={})
  finder => ?attr
```

== Has a `new` method that takes options in hash form, and has one such option called "finder" which pipes through to an attribute of the same name.

```
A>finder                            # ArrayRef[Str]
```

== AttributeMethod called "finder" that returns an ArrayRef of Str

```
->dumpconfig                        # HashRef
```

== Normal Method which expects no params and returns a hashref 

```
->_all_packages_for(options=[])     # ArrayRef[Str]
  0   =>   $file
```

Private method that takes parameters as a list, expecting only one argument, the first being a "file".

```
-~- Dist::Zilla::Role::MetaProvider::Provider
```

^ is a consumed role/parent class and related methods are under this section

```
[>] provides
```
== `provides` is a method required by this consumed role.

**Comment by kentfredric** [comment]
Please see how this compares in terms of obscurity: https://github.com/kentnl/Dist-Zilla-Plugin-MetaProvides-Package#quick-reference

The idea really has to work without too much explanation to be effective.

**Comment by dolmen** [comment]
Well, my point is that users of dzil plugins are interested mostly in how to use the plugin from a dist.ini.
Most dzil plugin documentation is not centered on the basic user needs, and from that point of view this quickref seems the worse of all I've seen so far.

I can understand that the perl API is interesting for the author, but it is only useful for developers that already have a deep knowledge of dzil hooking points.
I would prefer to see more documentation/examples on how to use the `finder` option from a `dist.ini` than the fact that it is an *attribute of the plugin object*.
And the quickref should be near the bottom of the page.

**Comment by karenetheridge** [comment]
agreed - for a dzil plugin, the most important documentation is how to use it in a dist.ini.  Programmatic APis are far less important, and for that I'd be most likely to simply look at the source anyway.
