### ISSUE TITLE
POD: incorrect documentation about default for `meta_noindex`

### ISSUE THREAD

**Issue by dolmen** [kentnl/Dist-Zilla-Plugin-MetaProvides-Package#5]
The documentation for the `meta_noindex` option says:

```
=item * meta_noindex = 0

By default, do nothing unusual.

=item * DEFAULT: meta_noindex = 1

When a module meets the criteria provided to L<< C<MetaNoIndex>|Dist::Zilla::Plugin::MetaNoIndex >>,
eliminate it from the metadata shipped to L<Dist::Zilla>
```

**What is the default value?**
"0 => *By default*, do nothing unusual" vs "* DEFAULT: meta_noindex = 1"

**Comment by kentfredric** [comment]
That is a confusing statement indeed. Its rather, 2 kinds of defaults.

I'm not even sure why it says that. Though I recall initially, the default was in fact 0.

**Comment by kentfredric** [comment]
https://metacpan.org/source/KENTNL/Dist-Zilla-Plugin-MetaProvides-Package-2.003000/Changes#L386

Aha. Yep. I dun goofed.

https://metacpan.org/diff/file?target=KENTNL/Dist-Zilla-Plugin-MetaProvides-Package-1.12044908/&source=KENTNL/Dist-Zilla-Plugin-MetaProvides-Package-1.11044404/#lib/Dist/Zilla/Plugin/MetaProvides/Package.pm 

```diff
 =over 4
  
-=item * DEFAULT: meta_noindex = 0
+=item * meta_noindex = 0
  
 By default, do nothing unusual.
  
-=item * meta_noindex = 1
+=item * DEFAULT: meta_noindex = 1
```

**Comment by dolmen** [comment]
Thanks!
